import torch
import torch.nn as nn
import torch.nn.functional as F
import math


class DoubleConv(nn.Module):
    """(convolution => [BN] => ReLU) * 2"""

    def __init__(self, in_channels, out_channels, mid_channels=None):
        super().__init__()
        if not mid_channels:
            mid_channels = out_channels
        self.double_conv = nn.Sequential(
            nn.Conv2d(in_channels, mid_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(mid_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(mid_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x):
        return self.double_conv(x)


class Down(nn.Module):
    """Downscaling with maxpool then double conv"""

    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.maxpool_conv = nn.Sequential(
            nn.MaxPool2d(2),
            DoubleConv(in_channels, out_channels)
        )

    def forward(self, x):
        return self.maxpool_conv(x)


class Up(nn.Module):
    """Upscaling then double conv"""

    def __init__(self, in_channels, out_channels, bilinear=True):
        super().__init__()

        # if bilinear, use the normal convolutions to reduce the number of channels
        if bilinear:
            self.up = nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
            self.conv = DoubleConv(in_channels, out_channels, in_channels // 2)
        else:
            self.up = nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2)
            self.conv = DoubleConv(in_channels, out_channels)

    def forward(self, x1, x2):
        x1 = self.up(x1)
        # input is CHW
        diffY = x2.size()[2] - x1.size()[2]
        diffX = x2.size()[3] - x1.size()[3]

        x1 = F.pad(x1, [diffX // 2, diffX - diffX // 2,
                        diffY // 2, diffY - diffY // 2])
        # if you have padding issues, see
        # https://github.com/HaiyongJiang/U-Net-Pytorch-Unstructured-Buggy/commit/0e854509c2cea854e247a9c615f175f76fbb2e3a
        # https://github.com/xiaopeng-liao/Pytorch-UNet/commit/8ebac70e633bac59fc22bb5195e513d5832fb3bd
        x = torch.cat([x2, x1], dim=1)
        return self.conv(x)


class OutConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(OutConv, self).__init__()
        self.conv = nn.Conv2d(in_channels, out_channels, kernel_size=1)

    def forward(self, x):
        return self.conv(x)
    
def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        print("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class Temporal(nn.Module):
    def __init__(self, in_channels_month, in_channels_day, out_channels):
        super(Temporal, self).__init__()

        self.temporal_month = nn.Sequential(
            nn.Linear(in_channels_month, out_channels),
            nn.BatchNorm1d(out_channels),
            nn.ReLU(inplace=True)
        )

        self.temporal_day = nn.Sequential(
            nn.Linear(in_channels_day, out_channels),
            nn.BatchNorm1d(out_channels),
            nn.ReLU(inplace=True)
        )

    def forward(self, x, first=False):
        if first is True:
            month, day = x[:, 0: 12], x[:, 12:]
        else:
            month, day = x
        f_month = self.temporal_month(month)
        f_day = self.temporal_day(day)
        return f_month, f_day, self.temporal_month(month) * self.temporal_day(day)


class UNet(nn.Module):
    def __init__(self, n_channels=10 + 1, n_classes=1, bilinear=False):
        super(UNet, self).__init__()
        self.n_channels = n_channels
        self.n_classes = n_classes
        self.bilinear = bilinear

        self.inc = (DoubleConv(n_channels, 32))
        self.down1 = (Down(32, 64))
        self.down2 = (Down(64, 128))
        self.down3 = (Down(128, 256))
        factor = 2 if bilinear else 1

        self.up2 = (Up(256, 128 // factor, bilinear))
        self.up3 = (Up(128, 64 // factor, bilinear))
        self.up4 = (Up(64, 32, bilinear))
        self.outc = (OutConv(32, n_classes))

        self.layer1 = nn.Sequential(
                nn.Conv2d(1, 16, kernel_size = 3, stride = 2, padding = 1),
                nn.BatchNorm2d(16),
                nn.ReLU(inplace=True),
                nn.Conv2d(16, 32, kernel_size=3, stride=2, padding=1),
                nn.BatchNorm2d(32),
                nn.ReLU(inplace=True),
                nn.Conv2d(32, 256, kernel_size=3, stride=2, padding=1),
                nn.BatchNorm2d(256),
                nn.ReLU(inplace=True),
        )

        # considering increase the complexity of this module
        self.compression_layer = nn.Sequential(
            nn.Conv2d(256 * 2, 256, kernel_size=(1, 1), stride=(1, 1)),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True)
        )

        self.temp1 = Temporal(in_channels_month=12, in_channels_day=31, out_channels=32)
        self.temp2 = Temporal(in_channels_month=32, in_channels_day=32, out_channels=64)
        self.temp3 = Temporal(in_channels_month=64, in_channels_day=64, out_channels=128)

        self.pos_embed = nn.Parameter(torch.zeros(1, 1, 600, 1440))
        trunc_normal_(self.pos_embed, std=.02)

    def forward(self, indicator1, indicator2, factor, today_embedding, target_embedding):
        b = indicator1.size(0)

        f_month1, f_day1, temporal01 = self.temp1(today_embedding, first=True)
        f_month2, f_day2, temporal11 = self.temp1(target_embedding, first=True)

        indicator1 = torch.cat([indicator1, self.pos_embed.repeat(b, 1, 1, 1)], dim=1)
        indicator2 = torch.cat([indicator2, self.pos_embed.repeat(b, 1, 1, 1)], dim=1)

        x01 = self.inc(indicator1) + temporal01[:, :, None, None]
        x11 = self.inc(indicator2) + temporal11[:, :, None, None]

        f_month1, f_day1, temporal02 = self.temp2((f_month1, f_day1))
        f_month2, f_day2, temporal12 = self.temp2((f_month2, f_day2))

        x02 = self.down1(x01) + temporal02[:, :, None, None]
        x12 = self.down1(x11) + temporal12[:, :, None, None]

        f_month1, f_day1, temporal03 = self.temp3((f_month1, f_day1))
        f_month2, f_day2, temporal13 = self.temp3((f_month2, f_day2))

        x03 = self.down2(x02) + temporal03[:, :, None, None]
        x13 = self.down2(x12) + temporal13[:, :, None, None]

        x04 = self.down3(x03) 
        x14 = self.down3(x13) 

        f1 = self.layer1(factor)
        x = self.compression_layer(torch.cat([x04 + f1, x14], dim=1))

        x = self.up2(x, x13) #+ temporal03[:, :, None, None]
        x = self.up3(x, x12) #+ temporal02[:, :, None, None]
        x = self.up4(x, x11) #+ temporal01[:, :, None, None]

        logits = self.outc(x)

        return torch.sigmoid(logits)
